### ISSUE TITLE
[Feature request] Could you create 2 role victoriametrics?

### ISSUE THREAD

**Issue by patsevanton** [buluma/ansible-role-victoriametrics#2]
Hello! Thanks for role prometheus

Could you create role [victoriametrics](https://victoriametrics.com/) for single and cluster install?

Example for cluster install https://github.com/VictoriaMetrics/ansible-playbooks

Example for single install (i think single) https://github.com/lotusnoir/ansible-apps_victoriametrics

**Comment by buluma** [comment]
[cluster install](https://galaxy.ansible.com/buluma/victoriametrics_cluster)

**Comment by patsevanton** [comment]
OMG! Awesome!

**Comment by patsevanton** [comment]
I try later

**Comment by patsevanton** [comment]
Thanks!!
